config/routes.rb
Rails.application.routes.draw do

  resources :advertising_platforms do
    match :advertisement, via: :get, on: :member

    resources :banners do
      member do
        get :reset
        get :click
      end
    end
  end

  root 'advertising_platforms#index'

end

app/models/advertising_platform.rb
class AdvertisingPlatform < ActiveRecord::Base
  has_many :banners, dependent: :destroy

  before_validation :set_platform_name #TODO before_save not works. Need better solution

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :platform_name, presence: true
  validates :url, presence: true, url: true

  def active?
    self.active
  end

  def relevant_banner
    self.banners.for_rotation.first
  end

  private
  def set_platform_name
    self.platform_name = self.name.parameterize('_') if self.name
  end
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  belongs_to :advertising_platform
  mount_uploader :image, ImageUploader

  validates :name, presence: true
  validates :url, presence: true, url: true
  validates :max_views_count, presence: true, numericality: { only_integer: true, greater_than: 0 }

  scope :for_rotation, -> { where(active: true).where('views_count < max_views_count').where.not(image: nil).order(views_count: :asc) }

  def enabled?
    self.active? && self.views_count <= self.max_views_count
  end

  def active?
    self.active
  end

  def increment_clicks!
    self.clicks_count += 1
    self.save
  end

  def increment_views!
    self.views_count += 1
    self.save
  end

  def reset_counters!
    self.clicks_count = 0
    self.views_count = 0
    self.save
  end
end

app/controllers/advertising_platforms_controller.rb
class AdvertisingPlatformsController < ApplicationController
  before_action :set_advertising_platform, except: [:index, :new]

  def index
    @advertising_platforms = AdvertisingPlatform.all
  end

  def new
    @advertising_platform = AdvertisingPlatform.new
  end

  def show
    @banners = @advertising_platform.banners.order(id: :asc)
  end

  def create
    @advertising_platform = AdvertisingPlatform.new(advertising_platform_params)
    respond_to do |format|
      if @advertising_platform.save
        format.html { redirect_to @advertising_platform, notice: 'Advertising platform successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @advertising_platform.update(advertising_platform_params)
        format.html { redirect_to @advertising_platform, notice: 'Advertising platform successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @advertising_platform.destroy
    respond_to do |format|
      format.html { redirect_to advertising_platforms_url, notice: 'Advertising platform successfully destroyed.' }
    end
  end

  def advertisement
    if @advertising_platform.active?
      if @banner = @advertising_platform.relevant_banner
        @banner.increment_views!
        respond_to do |format|
          format.html { render layout: false }
        end
        return
      end

    end

    respond_to do |format|
      format.html { render nothing: true, status: 401 }
    end
  end

  private
  def set_advertising_platform
    @advertising_platform ||= AdvertisingPlatform.find(params[:id])
  end

  def advertising_platform_params
    params.require(:advertising_platform).permit(:name, :url, :active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :set_banner, except: [:index, :new, :create]
  before_action :set_advertising_platform

  def index
    redirect_to @advertising_platform
  end

  def new
    @banner = @advertising_platform.banners.build
  end

  def create
    @banner = @advertising_platform.banners.build(banner_params)
    respond_to do |format|
      if @banner.save
        format.html { redirect_to advertising_platform_banner_path(@advertising_platform, @banner), notice: "Banner successfully created." }
      else
        format.html { redirect_to :new }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to advertising_platform_banner_path(@advertising_platform, @banner), notice: 'Banner successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @banner.destroy
    respond_to do |format|
      format.html { redirect_to @advertising_platform, notice: "Bunner successfully deleted."}
    end
  end

  def reset
    @banner.reset_counters!
    redirect_to :back
  end

  def click
    if @banner.enabled?
      @banner.increment_clicks!
      respond_to do |format|
        format.html { redirect_to @banner.url }
      end
    else
      respond_to do |format|
        format.html { redirect_to Settings.fallback.url }
      end
    end
  end

  private
  def set_banner
    @banner ||= Banner.find(params[:id])
  end

  def set_advertising_platform
    @advertising_platform ||= AdvertisingPlatform.find(params[:advertising_platform_id])
  end

  def banner_params
    params.require(:banner).permit(:name, :url, :max_views_count, :image, :remote_image_url, :remove_image, :active)
  end
end

app/helpers/advertising_platforms_helper.rb
module AdvertisingPlatformsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/advertising_platforms/_form.html.erb
<%= simple_form_for @advertising_platform do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :url %>
    <%= f.input :active %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to 'Cancel', advertising_platforms_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/advertising_platforms/advertisement.html.erb
<%= link_to click_advertising_platform_banner_path(@advertising_platform, @banner), :target => "_blank" do %>
  <%= image_tag @banner.image_url(:banner).to_s %>
<% end %>

app/views/advertising_platforms/edit.html.erb
<div class="row">
  <h1>Edit Advertising Platform</h1>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= render partial: 'form' %>
  </div>
</div>

app/views/advertising_platforms/index.html.erb
<div class="row">
  <h1>Advertising Platforms</h1>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= link_to 'New Platform', new_advertising_platform_path, class: 'btn btn-primary pull-right' %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Active</th>
          <th>Platform URL</th>
          <th>Banner URL</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @advertising_platforms.each do |platform| %>
          <tr>
            <th><%= platform.id %></th>
            <td><%= platform.name %></td>
            <td><%= platform.active %></td>
            <td><%= platform.url %></td>
            <td><%= advertisement_advertising_platform_url(platform) %></td>
            <td><%= link_to 'Show', advertising_platform_path(platform) %></td>
            <td><%= link_to 'Edit', edit_advertising_platform_path(platform) %></td>
            <td><%= link_to 'Delete', advertising_platform_path(platform), method: :delete, data: { confirm: 'Are you sure?'} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/advertising_platforms/new.html.erb
<div class="row">
  <h1>New Advertising Platform</h1>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= render partial: 'form' %>
  </div>
</div>

app/views/advertising_platforms/show.html.erb
<div class="row">
  <h1><%= @advertising_platform.name %> Banners</h1>
</div>

<div class="row">
  <div class="col-lg-12 text-right">
    <%= link_to 'New Banner', new_advertising_platform_banner_path(@advertising_platform), class: 'btn btn-primary' %>
    <%= link_to 'Back', advertising_platforms_path, class: 'btn btn-default' %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Active</th>
          <th>Clicks</th>
          <th>Views</th>
          <th>Max Views</th>
          <th colspan="4"></th>
        </tr>
      </thead>
      <tbody>
        <% @banners.each do |banner| %>
          <tr>
            <th><%= banner.id %></th>
            <td><%= banner.name %></td>
            <td><%= banner.active %></td>
            <td><%= banner.clicks_count %></td>
            <td><%= banner.views_count %></td>
            <td><%= banner.max_views_count %></td>
            <td><%= link_to 'Show', advertising_platform_banner_path(@advertising_platform, banner) %></td>
            <td><%= link_to 'Edit', edit_advertising_platform_banner_path(@advertising_platform, banner) %></td>
            <td><%= link_to 'Reset counters', reset_advertising_platform_banner_path(@advertising_platform, banner) %></td>
            <td><%= link_to 'Delete', advertising_platform_banner_path(@advertising_platform, banner), method: :delete, data: { confirm: 'Are you sure?'} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="instructions">
     <h4>Insert the banner url from the list above to your web site in a such way:</h4>
     <div class="snippet">
       <code>&lt;iframe src="<%= advertisement_advertising_platform_url(@advertising_platform) %>" frameBorder="0" width="200" heigth="200"&gt;&lt;/iframe&gt</code>
     </div>
   </div>
  </div>
</div>

app/views/banners/_form.html.erb
<%= simple_form_for([@advertising_platform, @banner]) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :url %>
    <%= f.input :max_views_count, input_html: { min: 1 } %>
    <%= f.input :remote_image_url %>
    <%= f.input :image, as: :file %>
    <%= f.input :remove_image, as: :boolean if @banner.persisted? %>
    <%= f.input :active %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to 'Cancel', advertising_platform_path(@advertising_platform), class: 'btn btn-default' %>
  </div>
<% end %>

app/views/banners/edit.html.erb
<div class="row">
  <h1>Edit '<%= @banner.name %>' banner</h1>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= render partial: 'form' %>
  </div>
</div>

app/views/banners/new.html.erb
<div class="row">
  <h1>New Banner</h1>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= render partial: 'form' %>
  </div>
</div>

app/views/banners/show.html.erb
<div class="row">
  <h1><%= @banner.name %></h1>
</div>

<div class="row">
  <div class="col-lg-12 text-right">
    <%= link_to 'Back', advertising_platform_path(@banner.advertising_platform_id), class: 'btn btn-default' %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="col-lg-6">
      <%= image_tag @banner.image_url(:thumb).to_s %>
    </div>
    <div class="col-lg-6">
      <dl class="dl-horizontal">
        <dt>Clicks</dt><dd><%= @banner.clicks_count %></dd>
        <dt>Views</dt><dd><%= @banner.views_count %></dd>
        <dt>Max Views</dt><dd><%= @banner.max_views_count %></dd>
        <dt>Active</dt><dd><%= @banner.active %></dd>
      </dl>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Banner System', root_path, class: 'navbar-brand' %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UltraBannerSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>